name: Validate Pull Request
on:
  workflow_call:

env:
  CUMULUSCI_SERVICE_github: '{"username": "${{ vars.GH_USER }}", "token": "${{ secrets.GH_TOKEN }}", "email": "cci@github.actions" }'

jobs:
  build-feature-test-package:
    name: "Build Feature Test Package"
    runs-on: ubuntu-latest
    steps:
      - uses: MyClubHub/cumulusci-build-feature-test-package@v2
        with:
          dev-hub-auth-url: ${{ secrets.SFDX_AUTH_URL }}
  feature-test-2gp:
    name: "Feature Test - 2GP"
    runs-on: ubuntu-latest
    needs:
      - build-feature-test-package
    steps:
      - uses: MyClubHub/cumulusci-feature-test-2gp@v2
        with:
          dev-hub-auth-url: ${{ secrets.SFDX_AUTH_URL }}
